jdk:
- oraclejdk8

env:
  global:
  - secure: LEHnuaZy1Stod7FhtL90zL3x1LOzhxz432IeLKodzqsad4jtuqn4CMEN3ADUM0mI/2/f0vVwRWzC59jsxotPmlw3CL/P5nKrxpZcj/ihCW4qJPTdTj+5YXFgdqHG4xsZf1NypweSHJz+O6w9SoCfqJxm5cRaWuiolKZuNgG0tu8itftFXkV61aTfIA2FuDKFY7VP0VrGBWKy84VbIVZz2sJMcaY9KAJjUJxw44ox+Swnd55E2hveHTxSgSc+gsCArZgTMQ/4EypZseq+1v8yyKExqj78O8I1sgSXDnU6+3AhXtw86BjfWYZXhAmzTUmoN8A8gJwmtev0lXLr7ouuynsJxpmTRn72/Yg64sZa2zrHfVUb9ikF8ItyRKC6Orx9PY/yAn2eLuyFEXXAKA7tjMHMSGHyPaeBRI4P58b6imFw6J9CMqqhL+KHb34tz/U2RpuXJImEu7tCANUmtpBiwcuBgNbLtmIO11mUsNQEVe79TlvPnIBZ2O4QTy/m4FU6KD8DxQYsZOKZPYvKqCKqjDW7uPaI6rjU4m5JEbxArTJ54afAQnlFYKPB3jWZzgyEjleil7wN3rLodw8m0Uxj6BaHlVGoUNVxEQfM7kEykswiaTncQGc1jB6F4WF4c/Hx9TV9gp+TzJGjp4NVCTYtqyDm72wuF3yr/YQcoqxuW9A=
  - secure: nTmp1XxnG23mU3mZOJF9LrvHfUSmL+fQiaxbQ9jaiyZihPegtLQUEE3Bq8USfgMjhWhcx/i/XClaP6ADBuSILKw7uRBCmZ2lBLf7oS+ekaBI0JjRrOe7l6ilM2X7Uh9xPqZEobm6o21ArYQtwCoRBDIu3geIIfmtzFhYhpSPIeKpZuW2rsBKzYdNczBdcDU6pgbBjv2itMkNufLfofPhHeTMEWmX2AfXe9kknl60CkvETSC42Pg7dguLO7XjK6US7uGTLBr73C8KidBSIQjp2ud7F9zCqVWyftFezgbBlRR0BotoGTOqOPYxWN0vXGrlTq9sNNweri1Dp/kmu9JKERwk9uaMjBsIPNYZqeCDE3uPjbx6rVvrKcRINtMO26lnSmH11BEgggvFi4eYjWKip+fmD4ramS+i18ecMeDoGaIpzdy+cy+L2g2S9MdVLERnlvUpo+LPpH61kqrYCfaNQ6Sy9lBX5cYHqEMA651ixUhVriTR+Zdyg4GALDdFN7GQEYtRHGnnrJWo4TBRLld6leOtj/wSoMCVfdaFsLd5XglxtMpzT0siunAEaRkfLkCwRmHHqKwBsIJ0WDo/Oq8ybC72Fi9lEVjrmuez0o/VqU/iSTDnOMfk+uwvmd+kSYlVafqcDg0FIUfyRaWMOPYaaI/DWPVeade9mtXNMYCQWmw=

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

script:
- mvn clean install -f pom.xml

after_success:
- chmod +x ./.travis/artifact-delete.sh
- chmod +x ./.travis/artifact-upload.sh
- "./.travis/artifact-delete.sh"
- "./.travis/artifact-upload.sh"

